version: '3'

services:
  oracle-db:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - "1521:1521"
      - "8080:8080"
      - "5500:5500"
    # restart: unless-stopped
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PWD=ORCL
      - ORACLE_SID=ORCL
    volumes:
      - ./oradata/data:/opt/oracle/oradata # persistent oracle database data.
      - ./oradata/scripts/setup:/opt/oracle/scripts/setup

